openapi: "3.0.0"
info:
  title: "Softtek NodeJS Demo API"
  version: "1.0.0"
paths:
  /usuarios:
    get:
      summary: "Obtiene una lista de usuarios"
      responses:
        '200':
          description: "Una lista de usuarios"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                    nombre:
                      type: "string"