// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "softtek-demo-expressjs",
    "version": "1"
  },
  "paths": {
    "/": {
      "any": {
        "summary": "app",
        "description": "",
        "operationId": "app.any./",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/{proxy+}": {
      "any": {
        "summary": "app",
        "description": "",
        "operationId": "app.any./{proxy+}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "proxy+",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/films": {
      "get": {
        "summary": "getFilms",
        "description": "",
        "operationId": "getFilms.get./films",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/people": {
      "get": {
        "summary": "getPeople",
        "description": "",
        "operationId": "getPeople.get./people",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planets": {
      "get": {
        "summary": "getPlanets",
        "description": "",
        "operationId": "getPlanets.get./planets",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/planet": {
      "post": {
        "summary": "createPlanet",
        "description": "",
        "operationId": "createPlanet.post./planet",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {},
  "host": "h1madjqatp5.execute-api.us-east-1.amazonaws.com/demo"
};